"""
Generate all possible visual outputs for the Fish Disease Detection System
- Confusion Matrix
- Grad-CAM visualizations for all 7 disease classes
"""

import os
import sys
from pathlib import Path
from predict import load_model, predict_image
from config import DATASET_DIR, CLASS_NAMES

def generate_all_gradcams():
    """Generate Grad-CAM visualizations for all 7 disease classes"""
    print("=" * 70)
    print("Generating Grad-CAM Visualizations for All Disease Classes")
    print("=" * 70)
    
    # Load model
    print("\n1. Loading model...")
    try:
        model = load_model()
        print("   [OK] Model loaded successfully!")
    except Exception as e:
        print(f"   [ERROR] Failed to load model: {e}")
        return
    
    # Create output directory
    output_dir = "results/gradcam_all_classes"
    os.makedirs(output_dir, exist_ok=True)
    print(f"\n2. Output directory: {output_dir}")
    
    # Generate Grad-CAM for each class
    print("\n3. Generating Grad-CAM for each disease class...")
    print("-" * 70)
    
    generated = 0
    failed = 0
    
    for class_name in CLASS_NAMES:
        class_dir = os.path.join(DATASET_DIR, class_name)
        
        if not os.path.exists(class_dir):
            print(f"   [SKIP] {class_name}: Directory not found")
            continue
        
        # Find image files
        image_extensions = ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']
        images = []
        for ext in image_extensions:
            images.extend(list(Path(class_dir).glob(f'*{ext}')))
        
        if not images:
            print(f"   [SKIP] {class_name}: No images found")
            continue
        
        # Use first image
        image_path = str(images[0])
        output_filename = class_name.lower().replace(' ', '_') + '_gradcam.png'
        output_path = os.path.join(output_dir, output_filename)
        
        print(f"\n   Processing: {class_name}")
        print(f"   Image: {os.path.basename(image_path)}")
        
        try:
            # Generate prediction and Grad-CAM
            result = predict_image(
                model, 
                image_path, 
                use_gradcam=True, 
                save_gradcam=output_path
            )
            
            predicted = result['predicted_class']
            confidence = result['confidence']
            
            print(f"   Prediction: {predicted} ({confidence:.2%})")
            print(f"   [OK] Saved: {output_path}")
            generated += 1
            
        except Exception as e:
            print(f"   [ERROR] Failed: {e}")
            failed += 1
    
    print("\n" + "=" * 70)
    print("Grad-CAM Generation Complete!")
    print("=" * 70)
    print(f"   Generated: {generated} visualizations")
    print(f"   Failed: {failed}")
    print(f"   Output directory: {output_dir}")
    print("\nAll Grad-CAM visualizations saved!")

def main():
    """Main function"""
    print("\n" + "=" * 70)
    print("Fish Disease Detection - Visual Output Generator")
    print("=" * 70)
    
    print("\nThis script will generate:")
    print("  - Grad-CAM visualizations for all 7 disease classes")
    print("\nNote: Confusion matrix is generated by running: python evaluate.py")
    
    # Auto-continue (non-interactive mode)
    print("\nStarting generation...")
    generate_all_gradcams()
    
    print("\n" + "=" * 70)
    print("Next Steps:")
    print("=" * 70)
    print("1. Run 'python evaluate.py' to generate confusion matrix")
    print("2. Check 'results/gradcam_all_classes/' for all Grad-CAM visualizations")
    print("3. Check 'results/confusion_matrix.png' for evaluation results")
    print("\nAll visual outputs are ready for your presentation!")

if __name__ == "__main__":
    main()

